# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='python_driver.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n!com.filipovski.gluon.python.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13python_driver.proto\" \n\x10\x45xecutionRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\">\n\x11\x45xecutionResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.OutputType*\x16\n\nOutputType\x12\x08\n\x04TEXT\x10\x00\x32I\n\x11PythonShellDriver\x12\x34\n\x07\x65xecute\x12\x11.ExecutionRequest\x1a\x12.ExecutionResponse\"\x00\x30\x01\x42%\n!com.filipovski.gluon.python.protoP\x01\x62\x06proto3'
)

_OUTPUTTYPE = _descriptor.EnumDescriptor(
  name='OutputType',
  full_name='OutputType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=121,
  serialized_end=143,
)
_sym_db.RegisterEnumDescriptor(_OUTPUTTYPE)

OutputType = enum_type_wrapper.EnumTypeWrapper(_OUTPUTTYPE)
TEXT = 0



_EXECUTIONREQUEST = _descriptor.Descriptor(
  name='ExecutionRequest',
  full_name='ExecutionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='ExecutionRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=55,
)


_EXECUTIONRESPONSE = _descriptor.Descriptor(
  name='ExecutionResponse',
  full_name='ExecutionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='ExecutionResponse.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ExecutionResponse.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=119,
)

_EXECUTIONRESPONSE.fields_by_name['type'].enum_type = _OUTPUTTYPE
DESCRIPTOR.message_types_by_name['ExecutionRequest'] = _EXECUTIONREQUEST
DESCRIPTOR.message_types_by_name['ExecutionResponse'] = _EXECUTIONRESPONSE
DESCRIPTOR.enum_types_by_name['OutputType'] = _OUTPUTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutionRequest = _reflection.GeneratedProtocolMessageType('ExecutionRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONREQUEST,
  '__module__' : 'python_driver_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionRequest)
  })
_sym_db.RegisterMessage(ExecutionRequest)

ExecutionResponse = _reflection.GeneratedProtocolMessageType('ExecutionResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONRESPONSE,
  '__module__' : 'python_driver_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionResponse)
  })
_sym_db.RegisterMessage(ExecutionResponse)


DESCRIPTOR._options = None

_PYTHONSHELLDRIVER = _descriptor.ServiceDescriptor(
  name='PythonShellDriver',
  full_name='PythonShellDriver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='execute',
    full_name='PythonShellDriver.execute',
    index=0,
    containing_service=None,
    input_type=_EXECUTIONREQUEST,
    output_type=_EXECUTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYTHONSHELLDRIVER)

DESCRIPTOR.services_by_name['PythonShellDriver'] = _PYTHONSHELLDRIVER

# @@protoc_insertion_point(module_scope)
