---
version: '3.9'

services:
    postgres:
        image: postgres:13.3
        hostname: postgres-db
        container_name: postgres-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_MULTIPLE_DATABASES: "core"
            POSTGRES_USER: "gluon"
            POSTGRES_PASSWORD: "gluon"
        volumes:
            - ../data/volumes/postgres/data:/var/lib/postgresql/data
            - ../data/volumes/postgres/scripts:/docker-entrypoint-initdb.d
