---
version: '3.9'

services:
    postgres:
        image: postgres:13.3
        hostname: postgres-db
        container_name: postgres-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_MULTIPLE_DATABASES: "core"
            POSTGRES_USER: "gluon"
            POSTGRES_PASSWORD: "gluon"
        volumes:
            - ../data/volumes/postgres/data:/var/lib/postgresql/data
            - ../data/volumes/postgres/scripts:/docker-entrypoint-initdb.d

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        hostname: kafka
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://192.168.1.101:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CREATE_TOPICS: "runs:3:1,run_messages:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
              
    schema-registry:
        image: confluentinc/cp-schema-registry:6.2.0
        container_name: schema-registry
        depends_on:
            - kafka
            - zookeeper
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

