server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.101:5432/core
    username: gluon
    password: gluon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: 192.168.1.101:9092
    properties:
      schema.registry.url: http://192.168.1.101:8081
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    #      specific.avro.reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
